
# Pull base image.
FROM ubuntu:18.04

# Set this before `apt-get` so that it can be done non-interactively
ENV DEBIAN_FRONTEND="noninteractive" \
    LANGUAGE="en_US.UTF-8"
ENV TZ America/New_York
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

# Install.
RUN /bin/bash <<EOF
apt-get update
apt-get update
apt-get install -y --no-install-recommends \
  build-essential \
  software-properties-common \
  curl \
  git \
  htop \
  net-tools \
  vim \
  wget \
  gnupg
git clone https://github.com/psmitty7373/cop.git
sed -i 's/sudo//g' cop/install-cop-bionic.sh
wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc |  apt-key add -
echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" |  tee /etc/apt/sources.list.d/mongodb-org-4.2.list
apt-get update
apt-get install -y mongodb-org mongodb-org-tools mongodb-org-shell mongodb-org-server mongodb-org-mongos
curl -sL https://deb.nodesource.com/setup_10.x |  bash -  
apt-get install -y nodejs
curl https://www.npmjs.com/install.sh |  sh
npm install -g browserify
npm install -g browser-pack-flat
npm install -g browser-unpack
npm install /cop
EOF

#RUN groupadd -r user && useradd -r -g user user
#USER user
# Add files.

# Set environment variables.
#ENV HOME /root

# Define working directory.
#WORKDIR /home/user

# Define default command.
COPY file /
ENTRYPOINT ["/bin/bash", "/docker-entrypoint.sh"]
#ENTRYPOINT ["/bin/bash"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
#CMD ["/bin/bash"]
CMD ["tail", "-f", "/dev/null"]
#curl -sL https://deb.nodesource.com/setup_12.x | bash -