apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cop
  name: cop
spec:
  containers:
  - image: andrewj84/cop:1.0.0
    name: cop
    env:
    - name: admin_pass
      value: admin
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
